### ISSUE TITLE
Plugin does not detect selection.

### ISSUE THREAD

**Issue by mxdanger** [Sleitnick/PIDebug#1]
I'm able to get the server running, which took a good hour to figure out what I need to download and the many commands to run before I could even do what was said in the readme.
![screenshot](https://user-images.githubusercontent.com/32040254/104685860-e0c26080-56b0-11eb-923e-56961ba49de4.png)

This is how I have the plugin set up. I'm saving the folder as the local plugin. This took me a good while to figure out too.
![screenshot](https://user-images.githubusercontent.com/32040254/104685467-f8e5b000-56af-11eb-99bd-546e65fcd781.png)

Just like in the videos this is how I have the data set up, which was fairly self-explanatory.
![screenshot](https://user-images.githubusercontent.com/32040254/104685619-5417a280-56b0-11eb-9a7d-b20d583fe8ef.png)

However, I for the life of me could not figure out how to fix the `OnSelectionChanged()` function so that it runs the module script `PIDSelection.new(selected)`.

```lua
local function OnSelectionChanged()
    print("select changed") --PRINTS
    local selected = Selection:Get()[1]
    if (selected and CollectionService:HasTag(selected, TAG)) then --NEVER RETURNS TRUE
        print("selected has tag") --NEVER PRINTS
        if (currentPidSelection) then
            if (currentPidSelection.PID == selected) then return end
            print("already selected else") --NEVER PRINTS
            ClearCurrentPIDSelection()
        end
        print("selected: "..selected) --NEVER PRINTS
        currentPidSelection = PIDSelection.new(selected)
    else
        print("else") --PRINTS
        ClearCurrentPIDSelection() --ALWAYS CLEARS SELECTION
    end
end
```

Hopefully, I'm not missing something obvious and if I ever get this working, I'm definitely going to make some changes to the readme to make this software as accessible as possible so people like me don't have to suffer without any layman's installation instructions.

**Comment by Sleitnick** [comment]
Hi, this application is still a work in progress.

For setup, all you need is node/npm installed and then run `npm install` within the project directory. I will add that to the readme.

Regarding PID selection, the PID implementation is important. You can use the following implementation. The `PID:Debug` function must be called for this to all work.

https://github.com/Sleitnick/PIDebug/blob/main/rbx/PID.lua
